name: Deploy dev.govradar.net

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: main
          name: node-backend
          path: ${{ github.workspace }}/backend
          repo: danielmoessner/node-backend.danielmoessner.de

          # token: ${{ secrets.TOKEN }}'
          # repository_owner: 'danielmoessner'
          # repository_name: 'node-backend.danielmoessner.de'
          # branch_name: 'main'
          # artifact_name: 'node-backend'
          # download_filename: 'backend.zip'

      - name: Unpack and run the backend
        run: unzip ${{ github.workspace }}/backend/backend.zip

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
