name: Test with node backend

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: main
          name: node-backend
          path: ${{ github.workspace }}/backend
          repo: danielmoessner/node-backend.danielmoessner.de

      - name: Install forever
        run: npm install forever -g

      - name: Run backend
        run: forever start backend/books.js

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:node
