name: Test with node backend

on:
  push:
    branches:
      - beispiel2

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the sales service
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: main
          name: order-service
          path: ${{ github.workspace }}/orders
          repo: danielmoessner/bachelorarbeit-orders
      
      - name: Install dependencies
        run: npm install request-promise-native -g
      
      - name: Install forever
        run: npm install forever -g

      - name: Run backend
        run: forever start orders/sales.js

      - name: Download the backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: beispiel1
          name: books-node-2
          path: ${{ github.workspace }}/backend
          repo: danielmoessner/node-backend.danielmoessner.de

      - name: Run backend
        run: forever start backend/books.js

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:node
