name: Test with django backend

on:
  push:
    branches:
      - beispiel2

jobs:
  test1:
    name: Run jest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the sales service
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: main
          name: order-service
          path: ${{ github.workspace }}/orders
          repo: danielmoessner/bachelorarbeit-orders
      
      - name: Install dependencies
        run: npm install request-promise-native -g
      
      - name: Install forever
        run: npm install forever -g

      - name: Run backend
        run: forever start orders/sales.js

      - name: Download the backend
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: create_artifact.yml
          workflow_conclusion: success
          branch: beispiel2
          name: books-django-2
          path: ${{ github.workspace }}/backend
          repo: danielmoessner/django-backend.danielmoessner.de

      - name: Install backend requirements
        run: pip install -r backend/requirements.txt

      - name: Run backend
        run: nohup python backend/manage.py runserver &

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test:django
